

spring:
  datasource:
    url: jdbc:postgresql://10.10.10.110:5432/tomato
    username: test
    password: test
    driver-class: org.postgresql.Driver
  abbitmq:
    host: localhost
    port: 5672
    username: guest1
    password: guest1

logging:
  level:
    com.murphy.springcloud: 'INFO'

test: this is from gitHub config center -- service-one-pro.yml
