server:
  port: 8762

spring:
  profiles: pro
  datasource:
    url: jdbc:postgresql://10.10.10.110:5432/tomato
    username: **
    password: **
    driver-class: org.postgresql.Driver

logging:
  level:
    com.murphy.springcloud: 'INFO'

test: this is from gitHub config center -- service one test.