server:
  port: 8761

spring:
  test:
    name: service-one1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

logging:
  level:
    com.murphy.springcloud: 'INFO'

test: this is from gitHub config center.

