server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: service-feign

service-one:
  domain: http://service-one
  api:
    hello: /hello