spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/tomato
    username: ota
    password: ota
    driver-class: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://192.168.20.61:5432/tomato
    username: ota
    password: ota
    driver-class: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.20.61:8760/eureka/

--- #在此配置各环境下的公共配置信息#
server:
  port: 8761

spring:
  application:
    name: service-one

logging:
  level:
    com.murphy.springcloud: 'DEBUG'

test: this is from local config -- application.yml

