server:
  port: 8761

spring:
  application:
    name: service-one

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

logging:
  level:
    com.murphy.springcloud: 'INFO'