spring:
  profiles: dev
  cloud:
    config:
      label: master
      profile: dev
      #uri: http://localhost:8888/
      #配置中心集群部署，通过负载均衡连接配置中心#
      discovery:
        enabled: true
        serviceId: config-server

---
spring:
  profiles: test
  cloud:
    config:
      label: master
      profile: test
      #uri: http://localhost:8888/
      discovery:
        enabled: true
        serviceId: config-server

--- #在此配置各环境下的公共配置信息#
spring:
  application:
    name: service-one
  cloud:
    config:
      testname: bbbb

