spring:
  profiles: dev
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/

---
spring:
  profiles: test
  cloud:
    config:
      label: master
      profile: test
      uri: http://localhost:8888/

---
spring:
  application:
    name: service-one
