spring:
  profiles: dev
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/

---
spring:
  profiles: test
  cloud:
    config:
      label: master
      profile: test
      uri: http://localhost:8888/

--- #在此配置各环境下的公共配置信息#
spring:
  application:
    name: service-one
  cloud:
    config:
      label: master1
      uri: http://localhost:8111/
      testname: bbbb

