server:
  port: 8780

spring:
  profiles: pro
  application:
    name: eureka-server-center

eureka:
  environment: dev
  # 当前服务器的主机IP。如果配置别名，按照官方文档的指示，需要修改当前服务器的/etc/hosts，指定每个配置中心所在服务器的主机别名：
  # 127.0.0.1 dev
  # 127.0.0.1 sim
  # 127.0.0.1 pro
  instance:
    hostname: pro
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://dev:8760/eureka/,http://sim:8770/eureka/