server:
  port: 8770

spring:
  profiles: simu
  application:
    name: eureka-server-center

eureka:
  environment: dev
  instance:
    hostname: simu
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://localhost:8760/eureka/,http://localhost:8780/eureka/
      defaultZone: http://dev:8760/eureka/,http://prod:8780/eureka/