server:
  port: 8760

spring:
  application:
    name: eureka-server-center

eureka:
  instance:
    hostname: localhost
  client:
    #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true。单个注册中心不需要注册自己，为false；集群为true。#
    registerWithEureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息，默认为true。同上，单个为false；集群为true#
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

## 保证注册中心的安全性
security:
  basic:
    enabled: false    #是否启用基础校验
  user:
    name: admin       #用户名
    password: admin   #密码