server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-one:
      path: /api-one/**
      # 如果service-one服务为分布式集群服务，则zuul网关服务利用ribbon实现负载均衡
      serviceId: service-one
    api-feign:
      path: /api-feign/**
      serviceId: service-feign
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon