# 在pom中集成dockerfile-maven-plugin进行镜像构建
FROM openjdk:8-jdk-alpine
MAINTAINER momo
VOLUME /tmp
ARG JAR_FILE
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/tmp/urandom", "-jar", "/app.jar"]