server:
  port: 8787

spring:
  application:
    name: config-server
  #配置中心从github上拉数据#
  cloud:
      config:
        label: master
        server:
          git:
            uri: https://github.com/mw312/springcloud
            searchPaths: springCloudConfig
      # 开启消息跟踪（GET方法调用：/trace）
      bus:
        trace:
          enabled: true
  # 开启rabbitmq实现异步消息推送（配置文件变更后通过POST方法触发配置中心的/bus/refresh，通过消息以及事件的形式实现各个客户端节点配置文件同步更新）
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

# 刷新时，关闭安全验证
management:
  security:
    enabled: false

logging:
  level:
    org.springframework.cloud: 'INFO'
