server:
  port: 8888

spring:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mw312/springcloud/
          searchPaths: springCloudConfig


