server:
  port: 8787

spring:
  application:
    name: config-server
  cloud:
      config:
        label: master
        server:
          git:
            uri: https://github.com/mw312/springcloud
            searchPaths: springCloudConfig
      # 开启消息跟踪
      bus:
        trace:
          enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

# 刷新时，关闭安全验证
management:
  security:
    enabled: false

logging:
  level:
    org.springframework.cloud: 'INFO'
