server:
  port: 8888

spring:
  application:
    name: config-server
  # 配置中心从github上拉数据 #
  cloud:
      config:
        label: master
        server:
          git:
            uri: https://github.com/mw312/springcloud
            searchPaths: springCloudConfig
      # 开启消息跟踪（GET方法调用：/trace）
      bus:
        trace:
          enabled: true
  # 开启rabbitmq实现异步消息推送[详见README.md]
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      # 注册中心开启基础校验后的连接配置 #
      defaultZone: http://admin:admin@localhost:8760/eureka/

# 保证actuator接口暴露的安全性
security:
  basic:
    enabled: true
    path: /config     #仅对/config路径的actuator接口进行认证【如果不配置客户端会因为权限问题连接不上此配置中心而报错】
  user:
    name: admin       #用户名
    password: admin   #密码

# 暴露actuator接口（例如：/bus/refresh; /health; /dump; /env; /metrics等）的安全策略
management:
  context-path: /config    #前缀
  port: 11111              #端口，为了和api接口使用的端口进行分离
  security:
    enabled: true          #是否需要安全保证

logging:
  level:
    org.springframework.cloud: 'INFO'





