server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  application:
    name: service-ribbon
  # Zipkin服务链路追踪服务器的地址
  zipkin:
    base-url: http://localhost:8989
  # 采样比例。默认为0.1，也就是只采样10%的比例。【测试环境设置为1，即全部采样。！！！生产环境切忌不要设置为1】
  # 在生成环境中，由于业务量比较大，所产生的跟踪数据可能会非常大，如果全部采集一是对业务有一定影响，二是对存储压力也会比较大，所以采样变的很重要。一般来说，我们也不需要把每一个发生的动作都进行记录。
  sleuth:
    sampler:
      percentage: 1.0

service-one:
  # 如果使用别名调用，restTemplate必须配置@LoadBalanced，利用ribbon进行负载均衡；反之如果使用服务的实际ip地址(http://localhost:8761)调问，restTemplate则不能配置@LoadBalanced。
  domain: http://service-one
  api:
    hello: /hello